### ISSUE TITLE
runApp() error

### ISSUE THREAD

**Issue by Domaine-2** [zhutiansheng/batch_server#3]
When I click Runapp in R，an error occurs just below
Error in source("src/MyCombat.R") : 
  src/MyCombat.R:182:3: unexpected symbol
181:   ####test inverse gamma distribution
182:   isInverseGamma
       ^

**Comment by zhutiansheng** [comment]
Please try https://github.com/zhutiansheng/BatchServer

**Comment by Domaine-2** [comment]
> Please try https://github.com/zhutiansheng/BatchServer

Thank you！The error no longer occurs while use codes in this version.
