### ISSUE TITLE
$ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by clsteam** [zhutiansheng/batch_server#5]
当我运行“conbat”这个步骤的时候
![1](https://user-images.githubusercontent.com/20498839/114962071-a7aaaf80-9e9c-11eb-95ac-054b2fda2d95.png)
然后，
![2](https://user-images.githubusercontent.com/20498839/114962084-aed1bd80-9e9c-11eb-9556-16b544719f0c.png)

然后我点击继续运行，就出现了“$ operator is invalid for atomic vectors”
我应该怎么解决呢？

谢谢，
yao

**Comment by zhutiansheng** [comment]
1，改用https://github.com/zhutiansheng/BatchServer试试
2，你的数据是否缺失值过多，或者每个批次的数据极少，batch和cancer是否有交叉设计等，还是不行的话，是否方便上传数据我检查下？

**Comment by clsteam** [comment]
我尝试使用了https://github.com/zhutiansheng/BatchServer，但是当我在绘制PVCA的图的时候出现闪退，并“错误: C stack usage  32364993 is too close to the limit”

以下是我的两个文件



[2.zip](https://github.com/zhutiansheng/batch_server/files/6322253/2.zip)

yao

**Comment by zhutiansheng** [comment]
从你的数据treat.csv可以看出这个批次并没有很好的设计，比如BATCH270114       64个样本都是celline的，这样这个批次信息无法有LC和Normal的信息，很多0表示没有对应的样本，自然没办法计算批次效应了。建议你看看Why Batch Effects Matter in Omics Data, and How to Avoid Them.这篇文章。
                          cancer
batch              CellLine  LC Normal
  BATCH142905        0   0      6
  BATCH153969        0   0      3
  BATCH163279        0  12     12
  BATCH227275        0   0      6
  BATCH257389        0  79      7
  BATCH270114       64   0      0
  BATCH320473        0 600     70
  BATCH343087        0   6      6
  BATCH34535         0   0     12
  BATCH380508        0   0      8
  BATCH380617        0   0      9
  PRJEB4337          0   0      8

**Comment by clsteam** [comment]
好的！
谢谢
